'use client';
/* eslint-disable @next/next/no-img-element */
import { useEffect, useRef, useState } from 'react';
import { Button } from './ui/button';
import { Input } from './ui/input';
import { Label } from './ui/label';
import { Textarea } from './ui/textarea';
import { ACTIONS, integer, safeName, type Clip, type FrameRef, type MotionSpec, type SheetSpec } from '@/lib/animation-types';
import { DIRECTIONS } from '@/lib/art-options';
import { DEFAULT_SETTINGS, MAX_UPLOAD_BYTES, MODELS, primaryVariant, type Job, type PixelSettings } from '@/lib/types';

const asset=(id:string,file:string)=>`/api/assets/${id}/${file}`;
const frameFile=(jobs:Job[],f:FrameRef)=>{const j=jobs.find(j=>j.id===f.jobId);return j?.animation?.frames[f.index]??(f.index===0?j?.variants[0]?.file:undefined)??`frame-${f.index}.png`;};
type ActionRow={action:string;frames:number;fps:number;loop:boolean;directions:string[]};
type Props={tab:'motion'|'sheet';jobs:Job[];settings:PixelSettings;apiKey:string;setApiKey:(s:string)=>void;hasKey:boolean;model:string;setModel:(s:string)=>void;quality:string;setQuality:(s:string)=>void;refresh:()=>Promise<void>;serverBusy:boolean;onBusy:(b:boolean)=>void;};
export function AnimationStudio(p:Props){
  const [sourceId,setSourceId]=useState(''),[refFile,setRefFile]=useState<File|null>(null),[refUrl,setRefUrl]=useState('');
  const [subject,setSubject]=useState('기준 캐릭터의 얼굴, 의상, 색상과 장비를 유지해 주세요.');
  const [weapon,setWeapon]=useState('원본 장비 유지'),[custom,setCustom]=useState('');
  const [width,setWidth]=useState(96),[height,setHeight]=useState(96),[bodyWidth,setBodyWidth]=useState(32),[bodyHeight,setBodyHeight]=useState(48);
  const [rows,setRows]=useState<ActionRow[]>(ACTIONS.map(([action,, ,frames,loop])=>({action,frames,fps:action==='idle'?6:10,loop,directions:action==='walk'?['down']:[]})));
  const [sheet,setSheet]=useState<SheetSpec>({name:'walk_down',cellWidth:48,cellHeight:48,columns:3,count:3,margin:0,spacing:0,start:0,fps:8,loop:true});
  const [nativeSize,setNativeSize]=useState(true),[sheetFile,setSheetFile]=useState<File|null>(null),[sheetUrl,setSheetUrl]=useState(''),[sheetSource,setSheetSource]=useState('');
  const [sheetDimensions,setSheetDimensions]=useState<{width:number;height:number}|null>(null);
  const [clips,setClips]=useState<Clip[]>([]),[selected,setSelected]=useState(''),[frame,setFrame]=useState(0),[playing,setPlaying]=useState(false),[zoom,setZoom]=useState(3);
  const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[rpg,setRpg]=useState(false),[progress,setProgress]=useState('');
  const [restore,setRestore]=useState(false),[regenText,setRegenText]=useState('');
  const stop=useRef(false),lock=useRef(false),refInput=useRef<HTMLInputElement>(null),sheetInput=useRef<HTMLInputElement>(null);
  const clip=clips.find(c=>c.id===selected)??clips[0],frameIndex=clip?Math.min(frame,clip.frames.length-1):0,current=clip?.frames[frameIndex];
  const totalCalls=rows.reduce((sum,r)=>sum+r.directions.length,0),totalFrames=rows.reduce((sum,r)=>sum+r.directions.length*r.frames,0);
  const disabled=busy||p.serverBusy;
  useEffect(()=>{const t=setTimeout(()=>{try{const saved=JSON.parse(localStorage.getItem('pixel-studio-animation-v1')??'[]');if(Array.isArray(saved)&&saved.length<=128)setClips(saved.filter(c=>c&&Array.isArray(c.frames)&&c.frames.length>0&&c.frames.length<=256));}catch{}setRestore(true);},0);return()=>clearTimeout(t);},[]);
  useEffect(()=>{if(restore)try{localStorage.setItem('pixel-studio-animation-v1',JSON.stringify(clips));}catch{}},[clips,restore]);
  useEffect(()=>{if(!refFile)return;const u=URL.createObjectURL(refFile),t=setTimeout(()=>setRefUrl(u),0);return()=>{clearTimeout(t);URL.revokeObjectURL(u);};},[refFile]);
  useEffect(()=>{if(!sheetFile)return;const u=URL.createObjectURL(sheetFile),t=setTimeout(()=>setSheetUrl(u),0);return()=>{clearTimeout(t);URL.revokeObjectURL(u);};},[sheetFile]);
  useEffect(()=>{if(!playing||!clip)return;const timer=setTimeout(()=>{if(frameIndex+1>=clip.frames.length&&!clip.loop){setPlaying(false);return;}setFrame((frameIndex+1)%clip.frames.length);},clip.frames[frameIndex].duration);return()=>clearTimeout(timer);},[playing,clip,frameIndex]);
  function updateClip(patch:Partial<Clip>){if(clip)setClips(cs=>cs.map(c=>c.id===clip.id?{...c,...patch}:c));}
  function updateFrame(patch:Partial<FrameRef>){if(clip)updateClip({frames:clip.frames.map((f,i)=>i===frameIndex?{...f,...patch}:f)});}
  function addJob(job:Job){const a=job.animation;if(!a)return;const id=crypto.randomUUID();setClips(cs=>{let name=a.name,n=2;while(cs.some(c=>c.name===name))name=`${a.name}_${n++}`;return [...cs,{id,name,width:a.width,height:a.height,fps:a.fps,loop:a.loop,frames:a.frames.map((_,index)=>({jobId:job.id,index,x:0,y:0,duration:Math.round(1000/a.fps)}))}];});setSelected(id);setFrame(0);setPlaying(false);}
  async function fileCheck(file:File){if(!file.size||file.size>MAX_UPLOAD_BYTES)throw new Error('50MB 이하 이미지를 선택해 주세요.');if(!['image/png','image/jpeg','image/webp'].includes(file.type))throw new Error('PNG, JPEG, WebP 이미지를 선택해 주세요.');const bitmap=await createImageBitmap(file);const d={width:bitmap.width,height:bitmap.height};bitmap.close();if(d.width*d.height>16_777_216)throw new Error('원본은 1,677만 픽셀 이하로 선택해 주세요.');return d;}
  function begin(){if(lock.current||disabled)return false;lock.current=true;setBusy(true);p.onBusy(true);setError('');setMessage('');setPlaying(false);stop.current=false;return true;}
  async function end(){lock.current=false;setBusy(false);p.onBusy(false);setProgress('');await p.refresh();}
  function reference(form:FormData){if(refFile)form.set('image',refFile);else if(sourceId){const j=p.jobs.find(j=>j.id===sourceId);form.set('sourceId',sourceId);form.set('sourceFile',j?.animation?.frames[0]??(j?primaryVariant(j)?.file:undefined)??'original.png');}else throw new Error('기준 캐릭터 파일이나 저장된 이미지를 먼저 선택해 주세요.');}
  async function generate(){
    if(!begin())return;
    try{
      if(!p.apiKey&&!p.hasKey)throw new Error('OpenAI API 키를 입력해 주세요.');if(!totalCalls)throw new Error('생성할 동작과 방향을 선택해 주세요.');
      integer(width,1,4096,'프레임 가로');integer(height,1,4096,'프레임 세로');integer(bodyWidth,1,width,'몸 가로');integer(bodyHeight,1,height,'몸 세로');
      let done=0;let batchPalette=p.settings.palette;
      for(const row of rows)for(const direction of row.directions){
        if(stop.current){setMessage(`${done}개 동작 저장 후 중단했습니다. 완료된 결과는 남아 있습니다.`);return;}
        setProgress(`${done+1} / ${totalCalls} · ${row.action}_${direction} 생성 중`);
        const form=new FormData();reference(form);form.set('id',crypto.randomUUID());form.set('apiKey',p.apiKey);form.set('model',p.model);form.set('quality',p.quality);form.set('prompt',subject);
        form.set('settings',JSON.stringify({...p.settings,width,height,size:Math.max(width,height),padding:0,exportSet:'selected',framing:'canvas',palette:batchPalette}));
        form.set('motion',JSON.stringify({action:row.action,direction,frames:row.frames,fps:row.fps,loop:row.loop,bodyWidth,bodyHeight,weapon,custom} satisfies MotionSpec));
        const r=await fetch('/api/edit',{method:'POST',headers:{'X-Pixel-Studio':'1'},body:form}),data=await r.json();if(!r.ok)throw new Error(data.error);
        addJob(data);if(!batchPalette&&data.animation?.palette?.length>=2)batchPalette=data.animation.palette;done++;await p.refresh();
      }
      setMessage(`${done}개 동작을 저장했습니다. 프레임을 검수하고 내보내세요.`);
    }catch(e){setError((e as Error).message+' 완료된 작업은 보존되며 실패한 요청을 자동 재시도하지 않습니다.');}finally{await end();}
  }
  async function importSheet(){if(!begin())return;try{
    const form=new FormData();form.set('id',crypto.randomUUID());form.set('sheet',JSON.stringify(sheet));
    const w=nativeSize?sheet.cellWidth:width,h=nativeSize?sheet.cellHeight:height;
    form.set('settings',JSON.stringify({...DEFAULT_SETTINGS,...p.settings,colors:p.settings.palette?.length??256,width:w,height:h,size:Math.max(w,h),padding:0,exportSet:'selected',framing:'canvas',sampling:'nearest'}));
    if(sheetFile)form.set('image',sheetFile);else if(sheetSource){form.set('sourceId',sheetSource);form.set('sourceFile','original.png');}else throw new Error('스프라이트 시트 파일을 선택해 주세요.');
    const r=await fetch('/api/animation/import',{method:'POST',headers:{'X-Pixel-Studio':'1'},body:form}),data=await r.json();if(!r.ok)throw new Error(data.error);addJob(data);setMessage(`${data.animation.frames.length}프레임을 분할했습니다. 다른 행도 시작 칸을 바꿔 추가할 수 있습니다.`);
  }catch(e){setError((e as Error).message);}finally{await end();}}
  async function exportClips(all:boolean){if(!begin())return;try{const chosen=all?clips:clip?[clip]:[];chosen.forEach(c=>safeName(c.name));const r=await fetch('/api/animation/export',{method:'POST',headers:{'Content-Type':'application/json','X-Pixel-Studio':'1'},body:JSON.stringify({clips:chosen,palette:p.settings.palette,rpgMaker:rpg&&all})});if(!r.ok){const d=await r.json();throw new Error(d.error);}const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download=all?'pixel-animation-project.zip':`${clip!.name}.zip`;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);setMessage('ZIP 다운로드 완료: PNG·GIF·Aseprite·Godot 파일이 들어 있습니다.');}catch(e){setError((e as Error).message);}finally{await end();}}
  async function regenerate(){if(!clip||!current||!begin())return;try{
    if(!p.apiKey&&!p.hasKey)throw new Error('OpenAI API 키를 입력해 주세요.');const job=p.jobs.find(j=>j.id===current.jobId),m=job?.animation?.motion;
    const form=new FormData();form.set('id',crypto.randomUUID());form.set('sourceId',current.jobId);form.set('sourceFile',frameFile(p.jobs,current));form.set('apiKey',p.apiKey);form.set('model',p.model);form.set('quality',p.quality);form.set('prompt',`${subject}\n${regenText}`);
    form.set('settings',JSON.stringify({...p.settings,size:Math.max(clip.width,clip.height),width:clip.width,height:clip.height,padding:0,framing:'canvas',exportSet:'selected'}));
    form.set('motion',JSON.stringify({...m,action:m?.action??'custom',direction:m?.direction??'down',frames:1,fps:clip.fps,loop:false,bodyWidth:Math.min(m?.bodyWidth??bodyWidth,clip.width),bodyHeight:Math.min(m?.bodyHeight??bodyHeight,clip.height),weapon:m?.weapon??weapon,custom:`${m?.custom??custom}\n${regenText}`,phase:{index:frameIndex,total:Math.min(16,clip.frames.length)}}));
    const r=await fetch('/api/edit',{method:'POST',headers:{'X-Pixel-Studio':'1'},body:form}),data=await r.json();if(!r.ok)throw new Error(data.error);updateFrame({jobId:data.id,index:0});setMessage('선택한 프레임을 새 결과로 교체했습니다. 이전 원본은 작업 기록에 남아 있습니다.');
  }catch(e){setError((e as Error).message);}finally{await end();}}
  const source=p.jobs.find(j=>j.id===sourceId),sourcePreview=refFile?refUrl:source?asset(source.id,source.animation?.frames[0]??primaryVariant(source)?.file??'original.png'):'';
  const sheetPreview=sheetFile?sheetUrl:sheetSource?asset(sheetSource,'original.png'):'';
  return <div className="animation-workspace"><div className="animation-builder">
    <section className="control-panel"><div className="panel-title"><h2>{p.tab==='motion'?'모션 만들기':'스프라이트 시트 가져오기'}</h2><span>{p.tab==='motion'?'AI · 유료':'LOCAL · 무료'}</span></div><div className="animation-controls"><fieldset disabled={disabled}>
      {p.tab==='motion'?<>
        <div className="reference-picker"><Label htmlFor="motionSource">기준 캐릭터</Label><select id="motionSource" value={refFile?'file':sourceId} onChange={e=>{setRefFile(null);setSourceId(e.target.value);}}><option value="">저장된 결과 선택</option>{refFile&&<option value="file">{refFile.name}</option>}{p.jobs.filter(j=>j.status==='complete').map(j=><option key={j.id} value={j.id}>{j.prompt.slice(0,65)}</option>)}</select><Button variant="outline" size="sm" onClick={()=>refInput.current?.click()}>내 컴퓨터의 기준 이미지 선택</Button><input hidden ref={refInput} type="file" accept="image/png,image/jpeg,image/webp" aria-label="모션 기준 이미지" onChange={async e=>{const f=e.target.files?.[0];e.target.value='';if(f)try{await fileCheck(f);setRefFile(f);setSourceId('');setError('');}catch(ex){setError((ex as Error).message);}}}/>{sourcePreview&&<img className="reference-preview checker" src={sourcePreview} alt="모션 생성 기준 캐릭터"/>}</div>
        <div className="field"><Label htmlFor="motionSubject">캐릭터 설명 · 선택 사항</Label><Textarea id="motionSubject" value={subject} maxLength={3500} onChange={e=>setSubject(e.target.value)}/></div>
        <div className="field-pair"><div className="field"><Label htmlFor="bodyWidth">몸 가로 px</Label><Input id="bodyWidth" type="number" min={1} max={width} value={bodyWidth} onChange={e=>setBodyWidth(Number(e.target.value))}/></div><div className="field"><Label htmlFor="bodyHeight">몸 세로 px</Label><Input id="bodyHeight" type="number" min={1} max={height} value={bodyHeight} onChange={e=>setBodyHeight(Number(e.target.value))}/></div></div>
        <div className="field-pair"><div className="field"><Label htmlFor="weapon">무기·장비</Label><Input id="weapon" value={weapon} maxLength={200} onChange={e=>setWeapon(e.target.value)}/></div><div className="field"><Label htmlFor="motionCustom">추가 동작 설명</Label><Input id="motionCustom" value={custom} maxLength={1000} onChange={e=>setCustom(e.target.value)} placeholder="예: 오른손에 도끼"/></div></div>
      </>:<>
        <div className="reference-picker"><Button variant="outline" onClick={()=>sheetInput.current?.click()}>스프라이트 시트 파일 선택</Button><input hidden type="file" ref={sheetInput} accept="image/png,image/jpeg,image/webp" aria-label="스프라이트 시트 파일" onChange={async e=>{const f=e.target.files?.[0];e.target.value='';if(f)try{const d=await fileCheck(f);setSheetFile(f);setSheetDimensions(d);setSheetSource('');setError('');}catch(ex){setError((ex as Error).message);}}}/><Label htmlFor="sheetSource">또는 저장된 원본 시트</Label><select id="sheetSource" value={sheetSource} onChange={e=>{setSheetSource(e.target.value);setSheetFile(null);setSheetDimensions(null);}}><option value="">선택하세요</option>{p.jobs.filter(j=>j.original).map(j=><option key={j.id} value={j.id}>{j.prompt.slice(0,65)}</option>)}</select>{sheetPreview&&<div className="sheet-source-preview checker"><img src={sheetPreview} alt="분할할 원본 시트" onLoad={e=>setSheetDimensions({width:e.currentTarget.naturalWidth,height:e.currentTarget.naturalHeight})}/></div>}{sheetDimensions&&<p className="help">원본 {sheetDimensions.width} × {sheetDimensions.height}px · {sheetFile?.name??'저장된 원본'}</p>}</div>
        <div className="field"><Label htmlFor="importName">추가할 동작 이름</Label><Input id="importName" value={sheet.name} onChange={e=>setSheet({...sheet,name:e.target.value})}/></div>
        <div className="sheet-input-grid">{([['cellWidth','셀 가로 px'],['cellHeight','셀 세로 px'],['columns','전체 열 수'],['count','가져올 프레임 수'],['start','시작 칸 (0부터)'],['margin','바깥 여백 px'],['spacing','칸 간격 px'],['fps','초당 프레임']] as const).map(([key,label])=><div className="field" key={key}><Label htmlFor={`sheet-${key}`}>{label}</Label><Input id={`sheet-${key}`} type="number" min={['margin','spacing','start'].includes(key)?0:1} value={sheet[key]} onChange={e=>setSheet({...sheet,[key]:Number(e.target.value)})}/></div>)}</div>
        <label className="checkbox-label"><input type="checkbox" checked={nativeSize} onChange={e=>setNativeSize(e.target.checked)}/>셀의 원래 픽셀 크기 유지</label><label className="checkbox-label"><input type="checkbox" checked={sheet.loop} onChange={e=>setSheet({...sheet,loop:e.target.checked})}/>반복 재생</label><p className="help">왼쪽 위 0번 칸부터 가로 방향으로 셉니다. 예: 3열 시트 두 번째 행은 시작 칸 3. 동작별로 필요한 행을 여러 번 추가하세요.</p>
      </>}
      {(p.tab==='motion'||!nativeSize)&&<><div className="field-pair"><div className="field"><Label htmlFor="motionWidth">프레임 전체 가로 px</Label><Input id="motionWidth" type="number" min={1} max={4096} value={width} onChange={e=>setWidth(Number(e.target.value))}/></div><div className="field"><Label htmlFor="motionHeight">프레임 전체 세로 px</Label><Input id="motionHeight" type="number" min={1} max={4096} value={height} onChange={e=>setHeight(Number(e.target.value))}/></div></div><p className="help">몸과 무기가 움직일 여유를 포함한 캔버스입니다. 모든 프레임에서 같은 크기·배치를 유지합니다.</p></>}
      {p.tab==='motion'&&<>
        <div className="field-pair"><div className="field"><Label htmlFor="motionModel">이미지 모델</Label><select id="motionModel" value={p.model} onChange={e=>p.setModel(e.target.value)}>{MODELS.map(m=><option key={m} value={m}>{m.endsWith('flare')?'2.5 Flare':'2.5 Sunburst'}</option>)}</select></div><div className="field"><Label htmlFor="motionQuality">생성 품질</Label><select id="motionQuality" value={p.quality} onChange={e=>p.setQuality(e.target.value)}><option value="low">빠른 초안</option><option value="medium">표준</option><option value="high">높음</option></select></div></div>
        <div className="field"><Label htmlFor="motionKey">OpenAI API 키</Label><Input id="motionKey" type="password" autoComplete="off" value={p.apiKey} placeholder={p.hasKey?'환경 변수 키 사용':'sk-…'} onChange={e=>p.setApiKey(e.target.value)}/><p className="help">현재 탭 메모리에만 보관합니다. 생성 탭과 공유합니다.</p></div>
      </>}
    </fieldset>{p.tab==='sheet'&&<Button className="generate-button" disabled={disabled||(!sheetFile&&!sheetSource)} onClick={importSheet}>시트 분할 후 재생 · 무료</Button>}</div></section>
    {p.tab==='motion'&&<section className="motion-matrix control-panel"><div className="panel-title"><h2>동작 × 방향</h2><span>GODOT</span></div><div className="animation-controls"><fieldset disabled={disabled}><div className="button-row"><Button size="sm" variant="outline" onClick={()=>setRows(rs=>rs.map(r=>({...r,directions:['idle','walk'].includes(r.action)?DIRECTIONS.slice(0,4).map(d=>d[0]):[]})))}>기본 4방향</Button><Button size="sm" variant="outline" onClick={()=>setRows(rs=>rs.map(r=>({...r,directions:['idle','walk','sword_slash','axe_chop'].includes(r.action)?DIRECTIONS.map(d=>d[0]):[]})))}>8방향 액션 세트</Button><Button size="sm" variant="ghost" onClick={()=>setRows(rs=>rs.map(r=>({...r,directions:[]})))}>선택 해제</Button></div><div className="matrix-scroll"><table><thead><tr><th>동작</th><th>프레임</th><th>FPS</th><th>반복</th>{DIRECTIONS.map(([d,label])=><th key={d} title={label}>{label.split(' ')[0]}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.action}><th>{ACTIONS[i][1]}</th><td><input aria-label={`${ACTIONS[i][1]} 프레임 수`} type="number" min={1} max={16} value={r.frames} onChange={e=>setRows(rs=>rs.map((x,k)=>k===i?{...x,frames:Number(e.target.value)}:x))}/></td><td><input aria-label={`${ACTIONS[i][1]} FPS`} type="number" min={1} max={60} value={r.fps} onChange={e=>setRows(rs=>rs.map((x,k)=>k===i?{...x,fps:Number(e.target.value)}:x))}/></td><td><input aria-label={`${ACTIONS[i][1]} 반복`} type="checkbox" checked={r.loop} onChange={e=>setRows(rs=>rs.map((x,k)=>k===i?{...x,loop:e.target.checked}:x))}/></td>{DIRECTIONS.map(([d,label])=><td key={d}><input aria-label={`${ACTIONS[i][1]} ${label}`} type="checkbox" checked={r.directions.includes(d)} onChange={e=>setRows(rs=>rs.map((x,k)=>k===i?{...x,directions:e.target.checked?[...x.directions,d]:x.directions.filter(v=>v!==d)}:x))}/></td>)}</tr>)}</tbody></table></div></fieldset><div className="batch-total"><strong>API {totalCalls}회 · 결과 {totalFrames}프레임</strong><p>동작·방향 하나당 시트 1장을 생성합니다. OpenAI 요금이 발생하며 자동 재시도하지 않습니다.</p></div><Button className="generate-button" disabled={disabled||!totalCalls||(!refFile&&!sourceId)} onClick={generate}>선택한 {totalCalls}개 동작 생성 · 유료</Button>{busy&&<Button variant="outline" className="stop-button" onClick={()=>{stop.current=true;setMessage('현재 요청이 끝나면 다음 동작부터 중단합니다.');}}>현재 요청 이후 중단</Button>}<p className="help">처음에는 한 방향 걷기부터 확인하세요. 고정 팔레트가 없으면 첫 시트에서 추출한 색상을 이번 묶음에 공유합니다.</p></div></section>}
  </div>
  <div aria-live="polite">{progress&&<div className="message success">{progress}</div>}{message&&<div className="message success">{message}</div>}{error&&<div className="message error" role="alert">{error}</div>}</div>
  <section className="animation-editor control-panel"><div className="panel-title"><h2>프레임 편집 · 재생 · 내보내기</h2><span>{clips.length} CLIPS</span></div><div className="editor-layout"><aside className="clip-list"><p className="help">작업 목록은 이 브라우저에 자동 저장됩니다.</p>{clips.map(c=><button disabled={busy} className={clip?.id===c.id?'selected':''} key={c.id} onClick={()=>{setSelected(c.id);setFrame(0);setPlaying(false);}}><strong>{c.name}</strong><small>{c.frames.length}프레임 · {c.width}×{c.height}px</small></button>)}<details><summary>저장된 모션 추가</summary>{p.jobs.filter(j=>j.animation&&j.status==='complete').map(j=><Button key={j.id} size="sm" variant="ghost" disabled={disabled} onClick={()=>addJob(j)}>{j.animation!.name} · {j.animation!.frames.length}F</Button>)}</details></aside>
  {clip&&current?<div className="clip-editor"><div className="playback-stage checker"><div className="playback-frame" style={{width:clip.width*zoom,height:clip.height*zoom}}><img src={asset(current.jobId,frameFile(p.jobs,current))} alt={`${clip.name} ${frameIndex+1}번째 프레임`} width={clip.width} height={clip.height} style={{width:clip.width*zoom,height:clip.height*zoom,transform:`translate(${current.x*zoom}px, ${current.y*zoom}px)`}}/><span className="foot-guide" style={{top:Math.round(clip.height*.85)*zoom}}/></div></div><div className="playback-controls"><Button size="sm" onClick={()=>{if(!playing&&frameIndex===clip.frames.length-1)setFrame(0);setPlaying(!playing);}}>{playing?'일시 정지':'▶ 재생'}</Button><Button size="sm" variant="outline" onClick={()=>{setPlaying(false);setFrame(Math.max(0,frameIndex-1));}}>이전</Button><span className="mono">{frameIndex+1} / {clip.frames.length}</span><Button size="sm" variant="outline" onClick={()=>{setPlaying(false);setFrame(Math.min(clip.frames.length-1,frameIndex+1));}}>다음</Button><Label htmlFor="animationZoom">배율</Label><select id="animationZoom" value={zoom} onChange={e=>setZoom(Number(e.target.value))}>{[1,2,3,4,6,8].map(n=><option key={n} value={n}>{n}×</option>)}</select></div>
    <fieldset disabled={disabled}><div className="clip-options"><div className="field"><Label htmlFor="clipName">동작 이름</Label><Input id="clipName" value={clip.name} maxLength={64} onChange={e=>updateClip({name:e.target.value})}/></div><div className="field"><Label htmlFor="clipFps">FPS · 전체 프레임에 적용</Label><Input id="clipFps" type="number" min={1} max={60} value={clip.fps} onChange={e=>{const fps=Number(e.target.value);if(fps>=1&&fps<=60)updateClip({fps,frames:clip.frames.map(f=>({...f,duration:Math.round(1000/fps)}))});}}/></div><label className="checkbox-label"><input type="checkbox" checked={clip.loop} onChange={e=>updateClip({loop:e.target.checked})}/>반복</label></div>
    <div className="frame-strip">{clip.frames.map((f,i)=><button key={i} aria-label={`프레임 ${i+1}`} className={frameIndex===i?'selected':''} onClick={()=>{setFrame(i);setPlaying(false);}}><img src={asset(f.jobId,frameFile(p.jobs,f))} alt=""/><span>{i+1}{clip.hitFrame===i?' · HIT':''}</span></button>)}</div>
    <div className="clip-options"><div className="field"><Label htmlFor="frameX">선택 프레임 X 이동</Label><Input id="frameX" type="number" min={-4096} max={4096} value={current.x} onChange={e=>updateFrame({x:Number(e.target.value)})}/></div><div className="field"><Label htmlFor="frameY">Y 이동 · 발 위치 조정</Label><Input id="frameY" type="number" min={-4096} max={4096} value={current.y} onChange={e=>updateFrame({y:Number(e.target.value)})}/></div><div className="field"><Label htmlFor="frameDuration">시간 ms</Label><Input id="frameDuration" type="number" min={10} max={60000} value={current.duration} onChange={e=>updateFrame({duration:Number(e.target.value)})}/></div></div>
    <div className="button-row"><Button size="sm" variant="outline" disabled={frameIndex===0} onClick={()=>{const a=[...clip.frames];[a[frameIndex-1],a[frameIndex]]=[a[frameIndex],a[frameIndex-1]];updateClip({frames:a,hitFrame:undefined});setFrame(frameIndex-1);}}>← 순서 앞으로</Button><Button size="sm" variant="outline" disabled={frameIndex===clip.frames.length-1} onClick={()=>{const a=[...clip.frames];[a[frameIndex+1],a[frameIndex]]=[a[frameIndex],a[frameIndex+1]];updateClip({frames:a,hitFrame:undefined});setFrame(frameIndex+1);}}>순서 뒤로 →</Button><Button size="sm" variant="outline" onClick={()=>{updateClip({frames:[...clip.frames.slice(0,frameIndex+1),{...current},...clip.frames.slice(frameIndex+1)],hitFrame:undefined});}}>복제</Button><Button size="sm" variant="ghost" disabled={clip.frames.length===1} onClick={()=>{updateClip({frames:clip.frames.filter((_,i)=>i!==frameIndex),hitFrame:undefined});setFrame(Math.max(0,frameIndex-1));}}>프레임 제외</Button><Button size="sm" variant="outline" onClick={()=>updateClip({hitFrame:clip.hitFrame===frameIndex?undefined:frameIndex})}>타격 시점 {clip.hitFrame===frameIndex?'해제':'표시'}</Button></div><p className="help">초록선은 발 기준선(높이의 85%)입니다. 이동 후 캔버스 밖 픽셀은 잘립니다. 타격 표시는 내보내기 메타데이터에 저장됩니다.</p>
    <details className="regen"><summary>선택 프레임 AI 수정 · 유료 1회</summary><Textarea aria-label="선택 프레임 수정 내용" value={regenText} onChange={e=>setRegenText(e.target.value)} maxLength={800} placeholder="예: 오른팔을 더 높이고 도끼를 머리 위로 들어 올려 주세요."/><Button size="sm" variant="outline" disabled={!regenText.trim()||clip.frames.length>16} onClick={regenerate}>이 프레임만 AI로 다시 그리기 · 유료</Button><p className="help">모션 탭의 API 키·모델·품질을 사용합니다. 원래 결과는 작업 기록에 보존됩니다.</p></details>
    <div className="export-section"><label className="checkbox-label"><input type="checkbox" checked={rpg} onChange={e=>setRpg(e.target.checked)}/>전체 ZIP에 RPG Maker MZ 걷기 시트 추가</label>{rpg&&<p className="help">walk_down / walk_left / walk_right / walk_up 필요. 각 방향의 0, N/3, 2N/3 프레임을 3패턴으로 배치하므로 정지·발걸음 순서를 확인하세요.</p>}<div className="button-row"><Button onClick={()=>exportClips(true)}>전체 프로젝트 ZIP 내보내기</Button><Button variant="outline" onClick={()=>exportClips(false)}>현재 동작 ZIP</Button><Button variant="ghost" onClick={()=>{setClips(cs=>cs.filter(c=>c.id!==clip.id));setSelected('');setFrame(0);setPlaying(false);}}>목록에서 동작 제외</Button></div><p className="help">Godot SpriteFrames · 장면 · Aseprite · 시트 PNG · 개별 PNG · 동작별 GIF · 메타데이터. 모두 로컬 처리, 무료입니다.</p></div>
    </fieldset></div>:<div className="canvas-empty"><h3>모션을 생성하거나 시트를 가져오세요.</h3><p>재생, 프레임 순서·속도·위치 조정과 게임용 내보내기를 여기에서 진행합니다.</p></div>}
  </div></section></div>;
}
