'use client';
/* eslint-disable @next/next/no-img-element */
import { useEffect,useRef,useState } from 'react';
import { Button } from './ui/button';
import { Input } from './ui/input';
import { Label } from './ui/label';
import { Textarea } from './ui/textarea';
import { MAX_UPLOAD_BYTES,MODELS,generationSize,primaryVariant,type Job,type PixelSettings } from '@/lib/types';
import type { TileGroup,TileSpec } from '@/lib/tiles';
import { CostEstimate, JobCost } from './cost-panel';
import { TerrainStudio } from './terrain-studio';
type Props={jobs:Job[];settings:PixelSettings;apiKey:string;setApiKey:(s:string)=>void;hasKey:boolean;model:string;setModel:(s:string)=>void;quality:string;refresh:()=>Promise<void>;serverBusy:boolean;onBusy:(b:boolean)=>void;};
export function TileStudio(p:Props){
  const [mode,setMode]=useState<'terrain'|'atlas'>('terrain');
  return <div><div className="button-row tile-mode"><Button disabled={p.serverBusy} variant={mode==='terrain'?'default':'outline'} onClick={()=>setMode('terrain')}>규격형 자동 연결 · 추천</Button><Button disabled={p.serverBusy} variant={mode==='atlas'?'default':'outline'} onClick={()=>setMode('atlas')}>기존 아틀라스 가져오기 / 자유 생성</Button></div>{mode==='terrain'?<TerrainStudio {...p}/>:<FreeTileStudio {...p}/>}</div>;
}
function FreeTileStudio(p:Props){
  const [file,setFile]=useState<File|null>(null),[url,setUrl]=useState(''),[sourceId,setSourceId]=useState(''),[size,setSize]=useState<{width:number;height:number}|null>(null);
  const [spec,setSpec]=useState<TileSpec>({tileWidth:16,tileHeight:16,columns:8,rows:8,margin:0,spacing:0,groups:[],terrainName:'Ground'});
  const [selected,setSelected]=useState({x:0,y:0}),[gw,setGw]=useState(1),[gh,setGh]=useState(1),[solid,setSolid]=useState(false),[terrain,setTerrain]=useState(false),[bits,setBits]=useState<number[]>([0,1,2,3,4,5,6,7]);
  const [zoom,setZoom]=useState(4),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[theme,setTheme]=useState('탑다운 RPG의 초록 잔디와 흙길. 잔디 중심, 가장자리, 바깥·안쪽 모서리와 작은 풀 장식.');
  const input=useRef<HTMLInputElement>(null),lock=useRef(false),job=p.jobs.find(j=>j.id===sourceId),sourceFile=job?primaryVariant(job)?.file??'original.png':'original.png';
  const preview=file?url:job?`/api/assets/${job.id}/${sourceFile}`:'';
  useEffect(()=>{if(!file)return;const u=URL.createObjectURL(file),t=setTimeout(()=>setUrl(u),0);return()=>{clearTimeout(t);URL.revokeObjectURL(u);};},[file]);
  const disabled=busy||p.serverBusy;
  function begin(){if(lock.current||disabled)return false;lock.current=true;setBusy(true);p.onBusy(true);setError('');setMessage('');return true;}
  async function end(){lock.current=false;setBusy(false);p.onBusy(false);await p.refresh();}
  function select(x:number,y:number){setSelected({x,y});const g=spec.groups.find(g=>x>=g.x&&x<g.x+g.w&&y>=g.y&&y<g.y+g.h);if(g){setSelected({x:g.x,y:g.y});setGw(g.w);setGh(g.h);setSolid(g.solid);setTerrain(g.terrain!==undefined);setBits(g.terrain??[0,1,2,3,4,5,6,7]);}else{setGw(1);setGh(1);setSolid(false);setTerrain(false);setBits([0,1,2,3,4,5,6,7]);}}
  function register(){setError('');if(!Number.isInteger(gw)||!Number.isInteger(gh)||gw<1||gh<1||selected.x+gw>spec.columns||selected.y+gh>spec.rows){setError('묶음이 시트 범위를 벗어납니다.');return;}const g:TileGroup={...selected,w:gw,h:gh,solid,terrain:terrain&&gw===1&&gh===1?bits:undefined};const previous=spec.groups.filter(x=>!(x.x===g.x&&x.y===g.y));if(previous.some(x=>g.x<x.x+x.w&&g.x+g.w>x.x&&g.y<x.y+x.h&&g.y+g.h>x.y)){setError('기존 묶음과 겹칩니다. 아래 목록에서 기존 묶음을 해제하세요.');return;}setSpec({...spec,groups:[...previous,g]});setMessage(`(${g.x}, ${g.y})에 ${g.w}×${g.h}칸 타일을 등록했습니다.`);}
  async function generate(){if(!begin())return;try{if(!p.apiKey&&!p.hasKey)throw new Error('API 키를 입력해 주세요.');const r=await fetch('/api/jobs',{method:'POST',headers:{'Content-Type':'application/json','X-Pixel-Studio':'1'},body:JSON.stringify({id:crypto.randomUUID(),apiKey:p.apiKey,model:p.model,quality:p.quality,prompt:theme,settings:p.settings,tiles:{...spec,groups:[],margin:0,spacing:0}})}),data=await r.json();if(!r.ok)throw new Error(data.error);await p.refresh();setFile(null);setSourceId(data.id);setSpec(s=>({...s,groups:[],margin:0,spacing:0}));setMessage('타일셋을 생성했습니다. 격자와 그림 경계를 확인하고 큰 오브젝트를 묶어 주세요.');}catch(e){setError((e as Error).message);}finally{await end();}}
  async function exportZip(){if(!begin())return;try{const form=new FormData();form.set('tiles',JSON.stringify(spec));if(p.settings.palette)form.set('palette',JSON.stringify(p.settings.palette));if(file)form.set('image',file);else if(sourceId){form.set('sourceId',sourceId);form.set('sourceFile',sourceFile);}else throw new Error('타일셋 이미지를 선택해 주세요.');const r=await fetch('/api/tiles/export',{method:'POST',headers:{'X-Pixel-Studio':'1'},body:form});if(!r.ok)throw new Error((await r.json()).error);const u=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=u;a.download='godot-tileset.zip';a.click();setTimeout(()=>URL.revokeObjectURL(u),30000);setMessage('Godot 타일셋 ZIP 다운로드 완료. README_ko.txt의 5단계대로 열면 됩니다.');}catch(e){setError((e as Error).message);}finally{await end();}}
  const gridValid=[spec.columns,spec.rows].every(n=>Number.isInteger(n)&&n>0)&&spec.columns*spec.rows<=4096;
  const fitsSource=!!size&&spec.margin+spec.columns*spec.tileWidth+(spec.columns-1)*spec.spacing<=size.width&&spec.margin+spec.rows*spec.tileHeight+(spec.rows-1)*spec.spacing<=size.height;
  return <div><div className="animation-builder"><section className="control-panel"><div className="panel-title"><h2>타일셋 생성 · 가져오기</h2><span>GODOT</span></div><div className="animation-controls"><fieldset disabled={disabled}>
    <div className="reference-picker"><Button variant="outline" onClick={()=>input.current?.click()}>타일셋 PNG 파일 선택</Button><input hidden type="file" ref={input} accept="image/png,image/jpeg,image/webp" aria-label="타일셋 파일" onChange={async e=>{const f=e.target.files?.[0];e.target.value='';if(f)try{if(f.size>MAX_UPLOAD_BYTES||!f.size)throw new Error('50MB 이하 파일을 선택해 주세요.');const b=await createImageBitmap(f);if(b.width*b.height>16_777_216){b.close();throw new Error('1,677만 픽셀 이하 이미지가 필요합니다.');}setSize({width:b.width,height:b.height});b.close();setFile(f);setSourceId('');setSpec(s=>({...s,groups:[]}));setError('');}catch(ex){setError((ex as Error).message);}}}/><Label htmlFor="tileSource">저장된 결과 사용</Label><select id="tileSource" value={sourceId} onChange={e=>{setSourceId(e.target.value);setFile(null);setSize(null);setSpec(s=>({...s,groups:[]}));}}><option value="">선택하세요</option>{p.jobs.filter(j=>j.status==='complete'&&!j.animation).map(j=><option key={j.id} value={j.id}>{j.prompt.slice(0,65)}</option>)}</select></div>
    <div className="tile-total">타일 한 칸 <strong>{spec.tileWidth}×{spec.tileHeight}px</strong><br/>시트 전체 <strong>{spec.tileWidth*spec.columns}×{spec.tileHeight*spec.rows}px</strong><br/><small>{spec.columns}열 × {spec.rows}행 = {spec.columns*spec.rows}칸</small></div>
    <div className="button-row">{[8,16,24,32,48,64].map(n=><Button key={n} size="sm" variant="outline" onClick={()=>setSpec({...spec,tileWidth:n,tileHeight:n,groups:[]})}>{n}px</Button>)}</div><div className="sheet-input-grid">{([['tileWidth','타일 한 칸 가로 px'],['tileHeight','타일 한 칸 세로 px'],['columns','가로 칸 수'],['rows','세로 칸 수'],['margin','원본 바깥 여백 px'],['spacing','원본 칸 간격 px']] as const).map(([key,label])=><div className="field" key={key}><Label htmlFor={`tile-${key}`}>{label}</Label><Input id={`tile-${key}`} type="number" min={key==='margin'||key==='spacing'?0:1} value={spec[key]} onChange={e=>setSpec({...spec,[key]:Number(e.target.value),groups:[]})}/></div>)}</div>
    {size&&<><p className="help">선택한 원본: {size.width}×{size.height}px</p><Button size="sm" variant="outline" onClick={()=>setSpec({...spec,columns:Math.max(1,Math.floor((size.width-spec.margin+spec.spacing)/(spec.tileWidth+spec.spacing))),rows:Math.max(1,Math.floor((size.height-spec.margin+spec.spacing)/(spec.tileHeight+spec.spacing))),groups:[]})}>원본 크기로 행·열 계산</Button></>}
    <details className="regen"><summary>새 타일셋 AI 생성 · 유료 1회</summary><Label htmlFor="tileTheme">타일셋 테마</Label><Textarea id="tileTheme" value={theme} maxLength={4000} onChange={e=>setTheme(e.target.value)}/><Label htmlFor="tileKey">OpenAI API 키</Label><Input id="tileKey" type="password" autoComplete="off" value={p.apiKey} placeholder={p.hasKey?'환경 변수 키 사용':'sk-…'} onChange={e=>p.setApiKey(e.target.value)}/><Label htmlFor="tileModel">이미지 모델</Label><select id="tileModel" value={p.model} onChange={e=>p.setModel(e.target.value)}>{MODELS.map(m=><option key={m} value={m}>{m}</option>)}</select><CostEstimate jobs={p.jobs} requests={[{model:p.model,quality:p.quality,apiSize:generationSize({...p.settings,width:spec.tileWidth*spec.columns,height:spec.tileHeight*spec.rows}),kind:'image',referenceCount:0}]}/><Button disabled={!theme.trim()} onClick={generate}>지정한 격자로 타일셋 생성 · 유료</Button><p className="help">타일 1칸 크기와 전체 배열을 AI에 함께 전달합니다. AI가 모든 경계와 연결을 정확히 지켰는지는 격자와 반복 미리보기로 확인해야 합니다.</p></details>
    </fieldset></div></section>
    <section className="control-panel"><div className="panel-title"><h2>칸 선택 · 큰 오브젝트 묶기</h2><span>ATLAS</span></div><div className="animation-controls"><div className="playback-controls"><Label htmlFor="tileZoom">정수 배율</Label><select id="tileZoom" value={zoom} onChange={e=>setZoom(Number(e.target.value))}>{[1,2,3,4,6,8].map(n=><option key={n} value={n}>{n}×</option>)}</select></div>{preview&&size?<div className="tile-stage checker"><div className="tile-canvas"><img src={preview} alt="타일 격자 원본" style={{width:size.width*zoom,height:size.height*zoom}}/><div className="tile-overlay">{gridValid&&Array.from({length:spec.columns*spec.rows},(_,i)=>{const x=i%spec.columns,y=Math.floor(i/spec.columns);return <button disabled={disabled} className={`tile-cell ${x>=selected.x&&x<selected.x+gw&&y>=selected.y&&y<selected.y+gh?'selected':''}`} key={i} aria-label={`타일 ${x}, ${y}`} title={`(${x}, ${y})`} style={{left:(spec.margin+x*(spec.tileWidth+spec.spacing))*zoom,top:(spec.margin+y*(spec.tileHeight+spec.spacing))*zoom,width:spec.tileWidth*zoom,height:spec.tileHeight*zoom}} onClick={()=>select(x,y)}/>;})}</div></div></div>:<div className="canvas-empty"><h3>타일셋 이미지를 선택하세요.</h3><p>128px 시트 / 16px 타일 → 8×8칸으로 표시합니다.</p></div>}{preview&&<img hidden src={preview} alt="" onLoad={e=>setSize({width:e.currentTarget.naturalWidth,height:e.currentTarget.naturalHeight})}/>}
    {preview&&!fitsSource&&<p className="message warning">격자가 원본 크기를 벗어납니다. 한 칸 크기와 여백을 확인하고 ‘원본 크기로 행·열 계산’을 누르세요.</p>}
    {preview&&size&&fitsSource&&<details className="regen"><summary>선택한 한 칸의 3×3 반복 미리보기</summary><div style={{overflow:'auto',maxHeight:320}}><div style={{display:'grid',gridTemplateColumns:`repeat(3, ${spec.tileWidth*zoom}px)`,width:spec.tileWidth*zoom*3}}>{Array.from({length:9},(_,i)=><div key={i} style={{width:spec.tileWidth*zoom,height:spec.tileHeight*zoom,overflow:'hidden'}}><img src={preview} alt="" style={{width:size.width*zoom,height:size.height*zoom,maxWidth:'none',imageRendering:'pixelated',transform:`translate(${-zoom*(spec.margin+selected.x*(spec.tileWidth+spec.spacing))}px, ${-zoom*(spec.margin+selected.y*(spec.tileHeight+spec.spacing))}px)`}}/></div>)}</div></div><p className="help">가운데 바닥 타일을 선택해 이음새와 반복 무늬를 확인하세요.</p></details>}
    <fieldset disabled={disabled}><p className="help">묶음의 왼쪽 위 칸을 클릭한 뒤 가로·세로 칸 수를 지정하세요. 지정하지 않은 불투명 칸은 1×1 타일로 자동 등록됩니다.</p><div className="clip-options"><div className="field"><Label htmlFor="groupWidth">묶음 가로 칸</Label><Input id="groupWidth" type="number" min={1} max={spec.columns} value={gw} onChange={e=>setGw(Number(e.target.value))}/></div><div className="field"><Label htmlFor="groupHeight">묶음 세로 칸</Label><Input id="groupHeight" type="number" min={1} max={spec.rows} value={gh} onChange={e=>setGh(Number(e.target.value))}/></div><div className="field"><Label>선택 위치</Label><span className="mono">({selected.x}, {selected.y}) · {gw*spec.tileWidth}×{gh*spec.tileHeight}px</span></div></div><label className="checkbox-label"><input type="checkbox" checked={solid} onChange={e=>setSolid(e.target.checked)}/>막힘 타일 · 사각형 충돌 추가</label>
    <details className="regen"><summary>지형 자동 연결 비트 설정 · 1×1 타일용</summary><label className="checkbox-label"><input type="checkbox" disabled={gw!==1||gh!==1} checked={terrain} onChange={e=>setTerrain(e.target.checked)}/>이 타일을 같은 지형으로 연결</label><Input aria-label="지형 이름" value={spec.terrainName} maxLength={60} onChange={e=>setSpec({...spec,terrainName:e.target.value})}/><div className="terrain-neighbors">{[0,1,2,3,-1,4,5,6,7].map((bit,i)=><button key={i} disabled={bit===-1||!terrain} className={bit===-1||bits.includes(bit)?'on':''} onClick={()=>setBits(bs=>bs.includes(bit)?bs.filter(b=>b!==bit):[...bs,bit])} aria-label={`연결 비트 ${i}`}>{bit===-1?'●':['↖','↑','↗','←','→','↙','↓','↘'][bit]}</button>)}</div><p className="help">초록 칸은 같은 지형과 맞닿는 방향입니다. 중심 타일은 모두 켜고, 가장자리는 바깥쪽을 끕니다. 안쪽 모서리 등 필요한 조합을 갖춰야 자연스럽게 연결됩니다.</p></details>
    <Button variant="outline" disabled={!preview||!fitsSource||!gridValid} onClick={register}>선택 영역 등록 / 갱신</Button><ul className="tile-group-list">{spec.groups.map(g=><li key={`${g.x},${g.y}`}>({g.x},{g.y}) · {g.w}×{g.h}칸 {g.solid?'· 충돌':''} {g.terrain!==undefined?'· 지형':''}<button onClick={()=>setSpec({...spec,groups:spec.groups.filter(x=>x!==g)})}>해제</button></li>)}</ul><Button className="generate-button" disabled={!preview||!fitsSource||!gridValid} onClick={exportZip}>Godot 타일셋 ZIP 내보내기 · 무료</Button>
    </fieldset></div></section></div>
    <div aria-live="polite">{job&&<JobCost job={job}/>}{busy&&<div className="message success">타일셋을 처리하고 있습니다…</div>}{message&&<div className="message success">{message}</div>}{error&&<div className="message error" role="alert">{error}</div>}</div>
    <section className="art-controls tile-guide"><strong>Godot에서 사용하는 순서</strong><ol><li>ZIP의 <b>pixel_tiles</b> 폴더를 프로젝트 루트에 복사합니다.</li><li><b>paint_here.tscn</b>을 열고 씬 트리의 <b>Ground</b>를 선택합니다.</li><li>아래쪽 <b>TileMap</b> 탭에서 타일을 선택하고 2D 화면에 칠합니다. <b>TileSet</b> 탭은 규격·충돌·연결을 설정하는 곳입니다.</li><li>기존 맵에는 <b>tileset.tres</b>를 TileMapLayer의 Tile Set에 지정하면 됩니다.</li></ol><p>내보내기에는 개별 타일, 큰 오브젝트 PNG, Aseprite 원본, Godot 리소스와 한글 설명서가 포함됩니다. 타일 한 칸 크기가 엔진 설정에 자동 반영됩니다.</p></section>
  </div>;
}
